from typing import Protocol


class EepromDevice(Protocol):
    def read(self) -> bytes: ...
    def write(self, data: bytes) -> None: ...


class ProfileRepository(Protocol):
    def load(self) -> dict: ...
    def save(self, data: dict) -> None: ...


class BootFiles(Protocol):
    def read(self, target: str) -> str: ...
    def write(self, target: str, content: str) -> str: ...
    def reboot(self) -> None: ...


class ConfigurationFiles(Protocol):
    def load(self, path: str) -> dict: ...
    def save(self, path: str, data: dict) -> None: ...


class HardwareProbe(Protocol):
    def detect(self) -> dict: ...


class ProfileSource(Protocol):
    def fetch(self) -> dict: ...
